---
sidebar: sidebar 
permalink: task-deploy-overview.html 
keywords: cloud compliance, data sense, get started, deploy cloud data sense, outbound internet, endpoints, cloud compliance internet, web browser connectivity, cloud compliance access, privacy, compliance, bluexp classification 
summary: Planen Sie, welche Bereitstellung von NetApp Data Classification Ihren Anforderungen entspricht. 
---
= NetApp Data Classification-Bereitstellungsmethoden
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Data Classification unterstützt verschiedene Bereitstellungsmethoden für unterschiedliche Netzwerk- und Verbindungsanforderungen. Die verfügbaren Methoden bieten Auswahlmöglichkeiten, sodass die am besten geeignete Option für Ihre Umgebung gewählt werden kann.

* link:task-deploy-cloud-compliance.html["Bereitstellung in der Cloud mithilfe der Konsole"] . Die Konsole stellt die Datenklassifizierungsinstanz im selben Cloud-Anbieternetzwerk bereit wie der Konsolenagent.
* link:task-deploy-compliance-onprem.html["Installation auf einem Linux-Host mit Internetzugang"]. Data Classification kann auf einem Linux-Host in Ihrem Netzwerk oder in der Cloud installiert werden. Diese Option kann nützlich sein, wenn lokale ONTAP-Systeme von einer Data Classification-Instanz vor Ort gescannt werden sollen, jedoch ist die Platzierung der Instanz vor Ort nicht zwingend erforderlich.
* link:task-deploy-compliance-dark-site.html["Installation auf einem Linux-Host an einem lokalen Standort ohne Internetzugang"], genannt _privater Modus._ Diese Art der Installation, die ein Installationsskript verwendet, hat keine Verbindung zur Console SaaS-Schicht.



TIP: Bei lokalen VMware vSphere-Bereitstellungen unterstützt die Datenklassifizierung eine vereinfachte link:task-deploy-ova.html["Bereitstellung mit OVA"].



[[on-premises-installation-script]]
== Installationsskript für die lokale Umgebung

Beide Installationsmethoden verwenden ein Installationsskript. Das Skript prüft, ob System und Umgebung die Voraussetzungen erfüllen. Ist dies der Fall, startet die Installation.

Es steht ein separates Softwarepaket zur Verfügung, um zu überprüfen, ob Ihr Linux-Host bereit ist. Zum Ausführen des Überprüfungspakets siehe link:task-test-linux-system.html["Überprüfen Sie, ob Ihr Linux-Host für die Installation von Data Classification bereit ist."].
