---
sidebar: sidebar 
permalink: task-scanning-overview.html 
keywords: cloud compliance, get started, enable cloud compliance, cifs credentials, smb credentials, cloud compliance access, privacy, compliance, dp volumes, data protection volumes, CVO, Cloud Volumes ONTAP, data sense, cloud data sense, map-only scans, map and classify, full 
summary: Scannen Sie Ihre Datenquellen mit NetApp Data Classification. 
---
= Scannen Sie Datenquellen mit NetApp Data Classification
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Data Classification scannt die Daten in den von Ihnen ausgewählten Repositories (den Volumes, Datenbankschemata oder anderen Benutzerdaten), um personenbezogene und sensible Daten zu identifizieren. Data Classification ordnet anschließend Ihre Organisationsdaten zu, kategorisiert jede Datei und identifiziert vordefinierte Muster in den Daten. Das Ergebnis des Scans ist ein Index mit personenbezogenen Informationen, sensiblen personenbezogenen Informationen, Datenkategorien und Dateitypen.

Nach dem ersten Scan scannt die Datenklassifizierung Ihre Daten kontinuierlich im Round-Robin-Verfahren, um inkrementelle Änderungen zu erkennen.  Aus diesem Grund ist es wichtig, die Instanz am Laufen zu halten.

Sie können Scans auf Volume-Ebene oder auf Datenbankschemaebene aktivieren und deaktivieren.



== Scanarten verstehen

Sie können in der Datenklassifizierung zwei Arten von Scans durchführen:

* **Nur-Karten-Scans** bieten lediglich einen groben Überblick über Ihre Daten und werden auf ausgewählten Datenquellen durchgeführt. Nur-Karten-Scans benötigen weniger Zeit als vollständige Scans, da sie nicht auf Dateien zugreifen, um die darin enthaltenen Daten zu sehen.
* **Vollständige Scans** bieten eine tiefgehende Überprüfung Ihrer Daten. Ein vollständiger Scan umfasst eine Kartierung und eine Klassifizierung der Daten innerhalb der Dateien.



TIP: Eine reine Map-only-Scan-Analyse kann hilfreich sein, um sich einen Überblick über Ihre Daten zu verschaffen und bestimmte Bereiche zu identifizieren, auf die vollständige Scans angewendet werden sollten.

Überprüfen Sie die Tabellen, um zu sehen, welche Informationen bei reinen Kartenscans und vollständigen Scans angezeigt werden.

[cols="47,18,18"]
|===
| Funktion | Vollständiger Scan | Nur-Map-Scan 


| Scangeschwindigkeit | Langsam | Schnell 


| Preise | Frei | Frei 


| Kapazität | Begrenzt auf 500 TiB* | Begrenzt auf 500 TiB* 


| Liste der Dateitypen und der verwendeten Kapazität | Ja | Ja 


| Anzahl der Dateien und genutzte Kapazität | Ja | Ja 


| Alter und Größe der Dateien | Ja | Ja 


| Fähigkeit zur Ausführung eineslink:task-controlling-governance-data.html["Datenzuordnungsbericht"] | Ja | Ja 


| Seite „Datenuntersuchung“ zum Anzeigen von Dateidetails | Ja | Nein 


| Suchen nach Namen in Dateien | Ja | Nein 


| Erstellenlink:task-using-policies.html["gespeicherte Abfragen"] die benutzerdefinierte Suchergebnisse bereitstellen | Ja | Nein 


| Möglichkeit, andere Berichte auszuführen | Ja | Nein 


| Möglichkeit, Metadaten aus Dateien anzuzeigen** | Ja | Ja 
|===
{asterisk}Die Datenklassifizierung beschränkt die Menge der gescannten Daten nicht. Jeder Console-Agent unterstützt das Scannen und Anzeigen von 500 TiB Daten. Um mehr als 500 TiB Daten zu scannen, link:https://docs.netapp.com/us-en/console-setup-admin/concept-connectors.html#connector-installation["einen anderen Konsolenagenten installieren"^] dann link:task-deploy-overview.html["eine weitere Data Classification-Instanz bereitstellen"]. + Die Console-Benutzeroberfläche zeigt Daten von einem einzelnen Connector an. Tipps zum Anzeigen von Daten mehrerer Console-Agents finden Sie unter link:https://docs.netapp.com/us-en/console-setup-admin/task-manage-multiple-connectors.html#switch-between-connectors["Arbeiten mit mehreren Konsolenagenten"^].

{asterisk}{asterisk} Die folgenden Metadaten werden während Mapping-Scans aus Dateien extrahiert:

* Uhrzeit der Dateierkennung
* Datei zuletzt aufgerufen
* Datei zuletzt geändert
* Dateityp
* Dateigröße
* Dateierstellung
* Anzahl der Dateien
* Berechtigungsextraktion
* Speicherrepository
* System
* Systemtyp
* Genutzte Kapazität


.Unterschiede im Governance-Dashboard:
[%collapsible]
====
[cols="40,25,25"]
|===
| Funktion | Vollständiger Scan | Nur-Map-Scan 


| Veraltete Daten | Ja | Ja 


| Nicht-geschäftliche Daten | Ja | Ja 


| Duplizierte Dateien | Ja | Ja 


| Vordefinierte gespeicherte Abfragen | Ja | Nein 


| Standardmäßig gespeicherte Abfragen | Ja | Ja 


| DDA-Bericht | Ja | Ja 


| Mapping-Bericht | Ja | Ja 


| Erkennung der Empfindlichkeitsstufe | Ja | Nein 


| Sensible Daten mit umfassenden Berechtigungen | Ja | Nein 


| Berechtigungen öffnen | Ja | Ja 


| Alter der Daten | Ja | Ja 


| Datenmenge | Ja | Ja 


| Kategorien | Ja | Nein 


| Dateitypen | Ja | Ja 
|===
====
.Unterschiede im Compliance-Dashboard:
[%collapsible]
====
[cols="40,25,25"]
|===
| Funktion | Vollständiger Scan | Nur-Map-Scan 


| Persönliche Informationen | Ja | Nein 


| Sensible persönliche Informationen | Ja | Nein 


| Bericht zur Bewertung des Datenschutzrisikos | Ja | Nein 


| HIPAA-Bericht | Ja | Nein 


| PCI DSS-Bericht | Ja | Nein 
|===
====
.Unterschiede bei den Untersuchungsfiltern:
[%collapsible]
====
[cols="40,25,25"]
|===
| Funktion | Vollständiger Scan | Nur-Map-Scan 


| Gespeicherte Abfragen | Ja | Ja 


| Systemtyp | Ja | Ja 


| System | Ja | Ja 


| Speicherrepository | Ja | Ja 


| Dateityp | Ja | Ja 


| Dateigröße | Ja | Ja 


| Erstellungszeit | Ja | Ja 


| Entdeckte Zeit | Ja | Ja 


| Zuletzt geändert | Ja | Ja 


| Letzter Zugriff | Ja | Ja 


| Berechtigungen öffnen | Ja | Ja 


| Dateiverzeichnispfad | Ja | Ja 


| Kategorie | Ja | Nein 


| Empfindlichkeitsstufe | Ja | Nein 


| Anzahl der Kennungen | Ja | Nein 


| personenbezogene Daten | Ja | Nein 


| Sensible personenbezogene Daten | Ja | Nein 


| Betroffene Person | Ja | Nein 


| Duplikate | Ja | Ja 


| Klassifizierungsstatus | Ja | Der Status ist immer „Eingeschränkte Einblicke“ 


| Scan-Analyseereignis | Ja | Ja 


| Datei-Hash | Ja | Ja 


| Anzahl der Benutzer mit Zugriff | Ja | Ja 


| Benutzer-/Gruppenberechtigungen | Ja | Ja 


| Dateieigentümer | Ja | Ja 


| Verzeichnistyp | Ja | Ja 
|===
====