= Version 1.40
:allow-uri-read: 




=== Version 1.40

Diese BlueXP classification Klassifizierungsversion enthält die folgenden Updates.

.Unterstützung für RHEL 9.5
Diese Version bietet zusätzlich zu den zuvor unterstützten Versionen Unterstützung für Red Hat Enterprise Linux v9.5.  Dies gilt für jede manuelle Vor-Ort-Installation der BlueXP classification, einschließlich Dark-Site-Bereitstellungen.

Die folgenden Betriebssysteme erfordern die Verwendung der Podman-Container-Engine und die BlueXP classification 1.30 oder höher: Red Hat Enterprise Linux Version 8.8, 8.10, 9.0, 9.1, 9.2, 9.3, 9.4 und 9.5.

.Priorisieren Sie Scans
Bei der Scan-Konfiguration können Sie die wichtigsten Scans priorisieren, sodass sie vor anderen Scans durchgeführt werden.  Diese Funktion ist hilfreich, wenn Sie über viele Arbeitsumgebungen verfügen und sicherstellen möchten, dass die Scans mit hoher Priorität zuerst erfolgreich durchgeführt werden.

Es gibt zwei Arten von Scans:

* *Nur-Mapping-Scans* bieten nur einen allgemeinen Überblick über Ihre Daten.  Das Mapping Ihrer Datenquellen kann sehr schnell durchgeführt werden, da zum Anzeigen der darin enthaltenen Daten kein Zugriff auf Dateien erforderlich ist.
* *Zuordnen und Klassifizieren*-Scans ermöglichen eine gründliche Überprüfung Ihrer Daten.


Sie können von der Verwendung von Nur-Mapping-Scans profitieren, um Ihre Daten schnell zu scannen und die Datenquellen zu identifizieren, die weiterer Recherche bedürfen. Später können Sie dann Map- und Klassifizierungsscans nur für diese erforderlichen Datenquellen oder Datenträger aktivieren.

Die Priorität wird nur reinen Mapping-Scans zugewiesen, nicht Mapping- und Klassifizierungs-Scans.

Die Priorität ist standardmäßig auf 1 eingestellt und Sie können sie auf eine beliebige Zahl zwischen 1 und 10 ändern.  Je niedriger die Zahl, desto höher die Priorität.  Wenn Sie keine Priorität festlegen, wird dem Scan die Priorität 5 zugewiesen.

Um die Priorität zu ändern, gehen Sie wie folgt vor:

. Wählen Sie im BlueXP classification *Konfiguration* aus.
. Wählen Sie die Ressourcen aus, die Sie priorisieren möchten.
. Wählen Sie unter der Option „Aktionen ...“ die Option „Scan priorisieren“ aus.


.Scans wiederholen
Mit dieser Version können Sie fehlgeschlagene Scans wiederholen.  Diese Funktion ist nützlich, wenn ein Scan aufgrund eines vorübergehenden Problems, beispielsweise eines Netzwerkausfalls, fehlgeschlagen ist.  Sie können den Scan wiederholen, ohne ihn neu konfigurieren zu müssen.

Um einen Scan erneut zu versuchen, gehen Sie wie folgt vor:

. Wählen Sie im BlueXP classification *Konfiguration* aus.
. Führen Sie einen der folgenden Schritte aus:
+
** Um alle fehlgeschlagenen Scans erneut durchzuführen, wählen Sie *Alle Scans wiederholen*.
** Um einen bestimmten Scan erneut zu versuchen, wählen Sie die Ressource aus und wählen Sie unter der Option „Aktionen …“ die Option „Scan erneut versuchen“.




Der Scan wird mit derselben Konfiguration wie der ursprüngliche Scan wiederholt.  Wenn der Scan erneut fehlschlägt, können Sie ihn beliebig oft wiederholen.
