= Version 1.49
:allow-uri-read: 




=== Version 1.49

Diese Version der Datenklassifizierung enthält Fehlerbehebungen und die folgenden Aktualisierungen:

.Überwachen Sie Kennzahlen und Leistung im Dashboard für die Gesundheitsüberwachung.
Die Datenklassifizierung bietet jetzt ein Dashboard zur Gesundheitsüberwachung, das eine Echtzeitüberwachung Ihrer Ressourcen sowie Einblicke in Speichernutzung, Festplattennutzung, Festplattenauslastung und mehr ermöglicht. Mithilfe der Erkenntnisse aus dem Dashboard zur Gesundheitsüberwachung können Sie die Infrastruktur Ihrer Bereitstellung überprüfen und Einblicke gewinnen, um Speicher und Leistung zu optimieren.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-data-classification/task-health-monitor.html["Überwachen Sie den Zustand der Datenklassifizierung"].

.Verbesserte Ladeleistung
Die Ladeleistung aller Seiten in der Datenklassifizierung wurde verbessert, um ein effizienteres Benutzererlebnis zu schaffen.
