= Verbesserte Darstellung des Scanfortschritts
:allow-uri-read: 




[[enhanced-scan-progress-clarity]]
=== Verbesserte Darstellung des Scanfortschritts

Die Scan-Konfigurationen beinhalten jetzt verbesserte Einblicke in den Scan-Abschluss. Bisher wurde ein Fortschrittsbalken nur während des Scanvorgangs angezeigt. Nun bleibt der Fortschrittsbalken auch nach Abschluss der Scans sichtbar, um zu bestätigen, dass diese erfolgreich durchgeführt wurden. Sie können auch die Anzahl der zugeordneten und gescannten Dateien einsehen.

Weitere Informationen zu den Scaneinstellungen finden Sie unter link:https://docs.netapp.com/us-en/data-services-data-classification/task-managing-repo-scanning.html#view-the-scan-status-for-your-repositories["Ändern Sie die NetApp Data Classification -Scaneinstellungen für Ihre Repositories"^]Die



[[general-improvements]]
=== Allgemeine Verbesserungen

Diese Version der Datenklassifizierung enthält Fehlerbehebungen, Sicherheitsverbesserungen und Leistungsoptimierungen.
