= Version 1.50
:allow-uri-read: 




=== Version 1.50

Diese Version der Datenklassifizierung enthält Fehlerbehebungen und die folgenden Aktualisierungen:

.Aktivieren Sie die Datenklassifizierung mit Amazon FSxN für ONTAP direkt aus der NetApp Console-Übersicht
Sie können Amazon FSxN für ONTAP-Systeme jetzt direkt von der NetApp Console-Oberfläche aus aktivieren, sodass Sie die Datenklassifizierung für Ihre FSxN-Systeme schneller starten können.

Weitere Informationen zur Verwendung von Data Classification mit Amazon FSxN für ONTAP finden Sie unter link:https://docs.netapp.com/us-en/data-services-data-classification/task-scanning-fsx.html["Amazon FSxN nach ONTAP-Volumes scannen"^].

.Erhöhtes Exportlimit für die Untersuchung von Verzeichnissen
Beim Export eines Untersuchungsberichts zu Verzeichnissen aus dem Untersuchungs-Dashboard können Sie nun 10.000 Zeilen einbeziehen. Diese Erhöhung gegenüber dem vorherigen Limit von 5.000 Zeilen unterstützt umfangreichere Untersuchungen im Bereich Daten-Governance und Compliance.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-data-classification/task-investigate-data.html["Daten untersuchen"^].

.Erhöhtes Limit für Kopieren und Verschieben
Beim Kopieren oder Verschieben von Dateien können Sie jetzt Dateien mit einer Größe von bis zu 250 MB kopieren oder verschieben, eine Erhöhung gegenüber dem vorherigen Limit von 50 MB.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/data-services-data-classification/task-investigate-data.html["Daten untersuchen"^].

.Verbesserte Darstellung für Bildschirme mit niedriger Auflösung
Data Classification hat die Anzeigeleistung für Bildschirme mit niedriger Auflösung verbessert und so die Benutzererfahrung verbessert.
